services:
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - database_data:/var/lib/mysql
        restart: unless-stopped

    mailcatcher:
        image: schickling/mailcatcher
        container_name: mailcatcher
        ports:
            - '1025:1025'
            - '1080:1080'
        restart: unless-stopped

volumes:
    database_data: