version: '3.7'

services:
    ###> doctrine/doctrine-bundle ###
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - database_data:/var/lib/mysql
        restart: unless-stopped
    ###< doctrine/doctrine-bundle ###
    mailcatcher:
        image: schickling/mailcatcher
        container_name: mailcatcher
        ports:
            - '1025:1025'
            - '1080:1080'
        restart: unless-stopped

# Example forumify docker-compose entry
#    forumify:
#        build: .
#        container_name: forumify
#        ports:
#            # The provided docker image relies on a proxy to provide HTTPS
#            - '8000:80'
#        environment:
#            - APP_DEBUG=0
#            - APP_ENV=prod
#            - APP_SECRET=replace-me-with-a-randomly-generated-string
#            - DATABASE_URL=mysql://username:password@mysql:3306/forumify?serverVersion=8.1.0
#            - MAILER_DSN=smtp:/username:password@hostname:25 # SMPT mailer
#            #- MAILER_DSN=ses://aws_key:aws_secret@default?region=region # AWS SES mailer
#            - DEFAULT_URI=https://not-a-real-forum.com
#        volumes:
#            - forumify_storage:/usr/src/app/public/storage

volumes:
    ###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###
#    forumify_storage:
